### PR TITLE
Maria hw 1

### PR DESCRIPTION
**Pull request by mkaramihaylova**

### CODE REVIEW

**Comment by kylebgorman** [comment]
Hi Maria,

Your edit is fine but you also checked in a file called `.DS_Store`. (This is some Mac OS X-specific metadata.) This doesn't belong in the repo. To remove it I think you'll want to do the following (not tested)

1. In the top-level directory for the HW1 branch of your fork of this repo, issue `git rm .DS_Store`
2. Issue `git commit -m "put a sensible commit message here" to stage the change.
3. Push the change to the HW1 branch of your fork...this will automatically add it to the PR. Confirm that the file is no longer part of the PR (see `Files changed`: it currently lists 2 files...)
4. Ping me (e.g., on this thread) and I'll review.

**Comment by mkaramihaylova** [comment]
Hi Kyle, 

After some help from Lucas, I believe I managed to delete the file. It looks like there may now be some merge conflicts though. Is there anything else I should do?

**Comment by kylebgorman** [comment]
Yes, that worked! I can handle the merge conflict on this side---it's a trivial one.

**Review by kylebgorman — APPROVED** [review]
LGTM, thanks for fixing the .DS_Store file.

**Pull request merged**
