### PR TITLE
added my name to the roster

### PR DESCRIPTION
**Pull request by your-future-self**
Added my username and email to the roster

### CODE REVIEW

**Review by kylebgorman — COMMENTED** [review]
Hi Lucas, two things:

* you use four spaces instead of tab. (see: https://unicoder.onrender.com/result?string=your-future-self+++++lucas.n.sass%40gmail.com+++++%0D%0A%0D%0A&normform=none&strip=true). Note that your text editor might be substituting four spaces when you hit the tab key and if so, you'll have to (temporarily) disable that.
* Even if you're not filling in pronouns, you still have to have a trailing tab. It's not a TSV file if there are a variable number of columns.

**Comment by your-future-self** [comment]
> Hi Lucas, two things:
> 
>     * you use four spaces instead of tab. (see: https://unicoder.onrender.com/result?string=your-future-self+++++lucas.n.sass%40gmail.com+++++%0D%0A%0D%0A&normform=none&strip=true). Note that your text editor might be substituting four spaces when you hit the tab key and if so, you'll have to (temporarily) disable that.
> 
>     * Even if you're not filling in pronouns, you still have to have a trailing tab. It's not a TSV file if there are a variable number of columns.

Hi I recommitted fixing the issues, do I have to open a new pull request? Or is a branch sort of perma-pull-requested until it's resolved

**Comment by kylebgorman** [comment]
> Hi I recommitted fixing the issues, do I have to open a new pull request? Or is a branch sort of perma-pull-requested until it's resolved

The latter! It's pretty convenient. So yes, your later commits are now here.

**Review by kylebgorman — COMMENTED** [review]
Issue 1 is now addressed-- there is a tab between the your username and name. However, you still need to address issue 2: the last line of the string needs to be a tab, too.

**Comment by your-future-self** [comment]
Hey Kyle, From everything I can see there is already a trailing tab-character on the line that I added. Here are some screenshots of what I can see from my end.

<h2>The commit showing the tab character at the end of the line: </h2>
Screenshot 2024-02-10 at 9 55 56 PM

<h2> The code file successfully showing a table (i believe) implying that it can see the final tab</h2>
Screenshot 2024-02-10 at 9 56 54 PM

**Review by kylebgorman — APPROVED** [review]
I see it now, thanks. Sorry for mistake there.

**Pull request merged**
